services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8080:80"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
